### ISSUE TITLE
mgoSim avg command 

### ISSUE THREAD

**Issue by wkpalan** [GuangchuangYu/GOSemSim#10]
In R, the description of msimGo function lists the command as **average** instead of **avg**.  t would be good to see the correct syntax from R help for the package itself. The change would be made in the 
[mgoSim.Rd](https://github.com/GuangchuangYu/GOSemSim/blob/72caecd9d5fc9d3a4b2fa484ea7b39c1e4d38266/man/mgoSim.Rd) file.

**Comment by GuangchuangYu** [comment]
thanks for your feedback. fixed now :)
