### ISSUE TITLE
NA semantic similarity scores for some MF terms

### ISSUE THREAD

**Issue by Best4Lex** [GuangchuangYu/GOSemSim#18]
Hi Guangchuang, 

Thanks for your work and I'm using GOSemSim to calculate pair-wise GO term semantic similarity scores. However, I faced with some issues when I tried to get the scores for some MF GO terms. They are:

[1] "GO:0140101"
[1] "GO:0140097"
[1] "GO:0140096"
[1] "GO:0140098"
[1] "GO:0015318"
[1] "GO:0140110" 

These GO terms are categorized into MF and are documented, but goSim() returned NA for them. The genome I used are human and yeast. Do you have any ideas why this issue occurred? I appreciate your help!

Best,
Linhua

**Comment by GuangchuangYu** [comment]
I did ask you to present a reproducible example and post it to github, but you just ignore my msg and copy your email.

You didn't provide minimal information for someone else to figure out the issue.

If you are using `Wang` method, which only rely on the GO Graph, the output is not `NA`, if you are using Information content methods, which are species-specific, you need to check out that whether these GO IDs are valid for the species.

For example, none of these GO IDs are used for human:

```
> go
[1] "GO:0140101" "GO:0140097" "GO:0140096" "GO:0140098" "GO:0015318"
[6] "GO:0140110"
> select(org.Hs.eg.db, keys = go, keytype="GO", "ENTREZID")
Error in .testForValidKeys(x, keys, keytype, fks) :
  None of the keys entered are valid keys for 'GO'. Please use the keys method to see a listing of valid arguments.
```
