### ISSUE TITLE
how to use mgenesem to compute for two different species

### ISSUE THREAD

**Issue by samKamal9** [GuangchuangYu/GOSemSim#22]
i am trying the following to get a matrix on human only. but i need for example  human vs Sc 
library(GOSemSim)
hsGO <- godata('org.Hs.eg.db', ont="MF")
mgeneSim(genes=c("835", "5261","241", "994"),
         semData=hsGO, measure = "Resnik", drop = "IEA", combine = "BMA")

**Comment by GuangchuangYu** [comment]
see <https://support.bioconductor.org/p/90063/>.
