### ISSUE TITLE
error: unable to open database file & workaround

### ISSUE THREAD

**Issue by mauritsunkel** [GuangchuangYu/GOSemSim#49]
Hi,

See in the picture what I tried, can't follow the code to find the error. Where the error should be I've tried to manually run the other lines to no avail.
![image](https://github.com/YuLab-SMU/GOSemSim/assets/47570265/c2acf4ca-7b5c-44d8-9047-53f68e328c50)

Do you have any idea? 
Is this an AnnotationDbi issue? 

Best,
Maus

**Comment by guidohooiveld** [comment]
I just happen to see this post, so better late than never... (and for the archive).

I hope your issue has been solved. That is, in essence your code is working in my hands. The warning can be ignored. Also, the 3rd line is not required for the function `godata`.
```

> library(GOSemSim)
> library(org.Hs.eg.db)
> 
> OrgDb=org.Hs.eg.db
> 
> GO <- godata(OrgDb=org.Hs.eg.db, ont="MF")
preparing gene to GO mapping data...
preparing IC data...
Warning message:
In godata(OrgDb = org.Hs.eg.db, ont = "MF") :
  use 'annoDb' instead of 'OrgDb'
> 
> GO
#
# DATA for Semantic Similarity calculation ...
#
> 
> str(GO)
Formal class 'GOSemSimDATA' [package "GOSemSim"] with 6 slots
  ..@ keys    : chr [1:18737] "1" "2" "9" "10" ...
  ..@ ont     : chr "MF"
  ..@ IC      : Named num [1:11153] Inf Inf 9.99 Inf 8.55 ...
  .. ..- attr(*, "names")= chr [1:11153] "GO:0000006" "GO:0000007" "GO:0000009" "GO:0000010" ...
  ..@ geneAnno:'data.frame':    87410 obs. of  4 variables:
  .. ..$ ENTREZID: chr [1:87410] "1" "2" "2" "2" ...
  .. ..$ GO      : chr [1:87410] "GO:0003674" "GO:0002020" "GO:0002020" "GO:0004866" ...
  .. ..$ EVIDENCE: chr [1:87410] "ND" "IBA" "IPI" "IBA" ...
  .. ..$ ONTOLOGY: chr [1:87410] "MF" "MF" "MF" "MF" ...
  ..@ tcssdata: list()
  ..@ metadata:'data.frame':    29 obs. of  2 variables:
  .. ..$ name : chr [1:29] "DBSCHEMAVERSION" "Db type" "Supporting package" "DBSCHEMA" ...
  .. ..$ value: chr [1:29] "2.1" "OrgDb" "AnnotationDbi" "HUMAN_DB" ...
> 
> packageVersion("GOSemSim")
[1] ‘2.32.0’
> 
> 
> 
```


Note: next time, please paste your code instead of copying a picture. The former will enable copy/pasting, the latter not. Also red on black might be difficult to read.

**Comment by mauritsunkel** [comment]
Hi, it's been some time, I believe in another setting I got it to work, thanks for replying!

**Comment by mauritsunkel** [comment]
Also, I will paste code next time :-)
